# Generated by Django 5.1.7 on 2025-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_submission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_assigned',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight'), ('nine', 'nine'), ('ten', 'ten')], default='one', max_length=10),
        ),
    ]
